# Generated by Django 5.2 on 2026-05-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'The race has been initialized'), ('in_progress', 'The race has started'), ('finished', 'The race is over')], default='init'),
        ),
    ]
