# Generated by Django 5.2 on 2026-06-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_run_count_run_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='count_run',
        ),
    ]
