# Generated by Django 5.2 on 2026-06-24 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0009_collectibleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='items',
            field=models.ManyToManyField(related_name='collectibleitems', to=settings.AUTH_USER_MODEL),
        ),
    ]
