# Generated by Django 5.2 on 2026-06-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_alter_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(null=True),
        ),
    ]
