# Generated by Django 5.2 on 2026-07-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_alter_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='seed',
            field=models.FloatField(null=True),
        ),
    ]
