# Generated by Django 5.2 on 2026-07-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_position_distance_position_seed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='seed',
            new_name='speed',
        ),
    ]
