# Generated by Django 5.2 on 2026-07-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0016_rename_seed_position_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
