# Generated by Django 5.2 on 2026-07-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_alter_position_distance_alter_position_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
    ]
