# Generated by Django 5.2 on 2026-08-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_subscribe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
