# Generated by Django 5.2 on 2026-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0022_alter_run_distance_alter_run_run_time_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
